---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring

