apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-staging
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1h
  path: ./deploy/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 20s

